label:          Classification
data_directory: /grand/projects/datascience/cadams/datasets/DUNE/pixsim_small/
train_file:     train.h5
test_file:      none.h5
val_file:       none.h5
imgaes:         3
access_mode:    random_blocks
dimension:      2
