label:          Classification
data_directory: /grand/projects/datascience/cadams/datasets/DUNE/pixsim_small/
train_file:     merged_sample_chunk8_100.h5
test_file:      none
val_file:       none.h5
access_mode:    random_blocks
dimension:      3
